/**
 * Structural mirror of the generic-work content types in
 * `src/library/types.ts` (Passage / Division / GenericWork / WorkAbout*),
 * used internally by the shared drama importer. Not one of the per-work
 * `data/<workId>/types.ts` outputs - those are generated byte-identical
 * copies (see typesTemplate.ts), exactly like the Archimedes/Isagoge pattern.
 */

export type Lang = 'grc' | 'en';

export interface Passage {
  /** printed line number of this passage's first line (e.g. "1", "96a",
   *  "1078a" for a non-numeric-suffix line); '' only for the dramatis
   *  personae Division's single Passage, which prints no line numbers */
  n: string;
  /** verbatim text: speaker name (as printed) on its own first line, then
   *  the speech's lines joined with "\n" (grc, verse) or a single space (en,
   *  prose runs joined into one paragraph) - see module docs. A stage
   *  direction or orphan paragraph passage carries no speaker-name line. */
  text: string;
  /** always null in this corpus (Perseus prints no per-passage citation
   *  beyond the line number already carried in `n`) */
  ref: string | null;
  /** optional note when something irregular was preserved */
  anomaly?: string;
}

export interface Division {
  /** 'dramatis-personae' for the cast-list division, else `card-N` (N = the
   *  card's first printed line number, as a string) */
  id: string;
  /** the card's first line number as printed, or null for dramatis-personae */
  number: string | null;
  /** "first–last" printed line-number span of this card's own <l n> lines,
   *  or null (dramatis-personae, or a card with no numbered line at all) */
  ref: string | null;
  /** the structural subtype in force where the card begins (e.g. "Episode",
   *  "Choral ode", "Strophe"), readable-cased; null if the card begins
   *  outside any structural div. "Dramatis Personae" (or the source's own
   *  Greek/Latin heading) for that special division. */
  sourceHeading: string | null;
  /** always null - no editorial gloss is added for any division in this corpus */
  editorialTitle: string | null;
  /** always [] - cards/dramatis-personae are both flat, one-level divisions */
  children: Division[];
  passages: Passage[];
}

export interface GenericWork {
  workId: string;
  language: Lang;
  divisions: Division[];
}

export interface WorkAboutSection {
  heading: string;
  paragraphs: string[];
}

export interface WorkAbout {
  workId: string;
  title: string;
  author: string;
  language: Lang;
  edition?: string;
  editor?: string;
  translator?: string;
  provenance: string;
  license: string;
  sections?: WorkAboutSection[];
}

export interface Anomaly {
  where: string;
  note: string;
}
