/**
 * Structural mirror of the generic-work content types in
 * `src/library/types.ts` (Passage / Division / GenericWork / WorkAbout*),
 * used internally by the Xenophon importer/validator.
 *
 * This file is NOT one of the 28 `data/xenophon-<slug>-{grc,en}/types.ts`
 * outputs - those are generated byte-identical (per language) copies, see
 * scripts/import-xenophon-shared/typesTemplate.ts - so each work directory
 * is self-contained. Kept here once so the importer/validator/driver share a
 * single TypeScript source of truth instead of importing from a generated
 * file that may not exist yet on a clean run.
 */

export type Lang = 'grc' | 'en';

export interface Passage {
  /** always '' - this source prints no paragraph numbers (only section numbers, folded into the parent Division - see about.json "Reference scheme") */
  n: string;
  /** verbatim paragraph text: entities decoded, NFC-normalised, whitespace collapsed */
  text: string;
  /** always null - see the work's about.json "Reference scheme" */
  ref: string | null;
  /** optional note when something irregular was preserved (e.g. an editorial <add>/<sic>/<corr>, or a <gap> lacuna) */
  anomaly?: string;
}

export interface Division {
  id: string;
  /** printed number as a string ('1'..'N'); never null for a leaf */
  number: string | null;
  /** always null - see the work's about.json */
  ref: string | null;
  /** Book only: the verbatim Greek source rubric (e.g. "Ἑλληνικῶν Α"); null everywhere else (English has no printed book rubric; chapters/sections have none) */
  sourceHeading: string | null;
  /** always null - no editorial gloss is added anywhere in this corpus */
  editorialTitle: string | null;
  /** non-empty only for a Book container in the 4 book-structured works */
  children: Division[];
  /** [] for a Book container; exactly one Passage for every leaf */
  passages: Passage[];
}

export interface GenericWork {
  workId: string;
  language: Lang;
  divisions: Division[];
}

export interface WorkAboutSection {
  heading: string;
  paragraphs: string[];
}

export interface WorkAbout {
  workId: string;
  title: string;
  author: string;
  language: Lang;
  edition?: string;
  editor?: string;
  translator?: string;
  provenance: string;
  license: string;
  sections?: WorkAboutSection[];
}
