/**
 * One-off assembly helper (NOT part of the shipped importer): combines
 * raw/corrected-text/page307.txt .. page408.txt (pages 307-336 generated by
 * genProofreadPages.mjs from the Wikisource-proofread wikitext with the one
 * word-level fix found on page 329; pages 337-408 hand-transcribed against
 * the page images during this recovery, per raw/corrections-log.json) into
 * a single raw/corrected-pages.json cache: an array of
 * {page, qualityLevel, text} covering the full 307-409 range (409 has no
 * reading-text content - it is the book's own back-matter index page,
 * confirmed by direct inspection - and is included with text: "" only so
 * the array covers the whole 103-page range this recovery reviewed).
 *
 * Run once: node raw/scratch/buildCorrectedPagesJson.mjs
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const RAW_DIR = join(HERE, '..');
const TEXT_DIR = join(RAW_DIR, 'corrected-text');

const rawPages = JSON.parse(readFileSync(join(RAW_DIR, 'pages-307-409.json'), 'utf8'));
const qualityByPage = new Map();
for (const p of rawPages) {
  const m = /\/(\d+)$/.exec(p.title);
  const q = /<pagequality level="(\d)"/.exec(p.content);
  qualityByPage.set(Number(m[1]), q ? Number(q[1]) : null);
}

const out = [];
for (let n = 307; n <= 409; n++) {
  const file = join(TEXT_DIR, `page${n}.txt`);
  const text = existsSync(file) ? readFileSync(file, 'utf8').replace(/\n+$/, '') : '';
  out.push({ page: n, qualityLevel: qualityByPage.get(n) ?? null, text });
}

writeFileSync(join(RAW_DIR, 'corrected-pages.json'), JSON.stringify(out, null, 2) + '\n', 'utf8');
process.stdout.write(`wrote ${out.length} pages (${out.filter((p) => p.text.length > 0).length} with text)\n`);
