/**
 * Structural mirror of the generic-work content types in
 * `src/library/types.ts` (Passage / Division / GenericWork / PassageFigure /
 * WorkAbout*), used internally by the Archimedes importer/validator.
 *
 * This file is NOT one of the 13 `data/archimedes-<slug>/types.ts` outputs -
 * those are generated byte-identical copies (see
 * scripts/import-archimedes/typesTemplate.ts) so each work directory is
 * self-contained, exactly like data/isagoge-grc/types.ts. Kept here once so the
 * importer/validator/driver share a single TypeScript source of truth instead
 * of importing from a generated file that may not exist yet on a clean run.
 */

export interface PassageFigure {
  image?: string;
  imageWidth?: number;
  imageHeight?: number;
  alt?: string;
  source: string;
  note?: string;
  /** further distinct printed figures on the same passage (mirrors src/library/types.ts) */
  more?: Array<{ image: string; imageWidth: number; imageHeight: number; alt?: string }>;
}

export interface Passage {
  n: string;
  text: string;
  ref: string | null;
  anomaly?: string;
  figure?: PassageFigure;
}

export interface Division {
  id: string;
  number: string | null;
  ref: string | null;
  sourceHeading: string | null;
  editorialTitle: string | null;
  children: Division[];
  passages: Passage[];
}

export interface GenericWork {
  workId: string;
  language: 'grc';
  divisions: Division[];
}

export interface WorkAboutSection {
  heading: string;
  paragraphs: string[];
}

export interface WorkAbout {
  workId: string;
  title: string;
  author: string;
  language: 'grc';
  edition?: string;
  editor?: string;
  translator?: string;
  provenance: string;
  license: string;
  sections?: WorkAboutSection[];
}
