/**
 * Structural mirror of the generic-work content types in
 * `src/library/types.ts` (Passage / Division / GenericWork / WorkAbout*),
 * used internally by the Plutarch importer/validator. Mirrors
 * scripts/import-archimedes-shared/genericTypes.ts.
 *
 * This file is NOT one of the 132 `data/plutarch-<slug>-{grc,en}/types.ts`
 * outputs - those are generated byte-identical copies (see
 * scripts/import-plutarch-shared/typesTemplate.ts) so each work directory is
 * self-contained. Kept here once so the importer/validator/driver share a
 * single TypeScript source of truth instead of importing from a generated
 * file that may not exist yet on a clean run.
 */

export type Lang = 'la' | 'grc' | 'en';

export interface PassageFigure {
  image?: string;
  imageWidth?: number;
  imageHeight?: number;
  alt?: string;
  source: string;
  note?: string;
}

export interface Passage {
  n: string;
  text: string;
  ref: string | null;
  anomaly?: string;
  figure?: PassageFigure;
}

export interface Division {
  id: string;
  number: string | null;
  ref: string | null;
  sourceHeading: string | null;
  editorialTitle: string | null;
  children: Division[];
  passages: Passage[];
}

export interface GenericWork {
  workId: string;
  language: Lang;
  divisions: Division[];
}

export interface WorkAboutSection {
  heading: string;
  paragraphs: string[];
}

export interface WorkAbout {
  workId: string;
  title: string;
  author: string;
  language: Lang;
  edition?: string;
  editor?: string;
  translator?: string;
  provenance: string;
  license: string;
  sections?: WorkAboutSection[];
}
