/**
 * The 66-entry ground-truth table for Plutarch's Parallel Lives (Perseus
 * canonical-greekLit, CTS urn:cts:greekLit:tlg0007.tlgNNN), tlg001-tlg066 -
 * 48 Lives + 18 Comparisons (tlg067+ is the Moralia, out of scope).
 *
 * Every field below (title, Greek label, witness id, volume, year) was read
 * directly from each work's own __cts__.xml (fetched once into
 * scripts/import-plutarch/raw/catalogs/), never assumed. Witnesses are
 * perseus-grc2/perseus-eng2 for 63 of the 66 works; three exceptions,
 * confirmed the same way:
 *   - tlg001 (Theseus): English is perseus-eng3, not perseus-eng2.
 *   - tlg051 (Agis and Cleomenes) and tlg052 (Tiberius and Caius Gracchus):
 *     both Greek and English are the perseus-grc1/perseus-eng1 witnesses.
 *
 * Structural note - the two "double lives" (tlg051, tlg052): unlike every
 * other work, their perseus-grc1/-eng1 witnesses carry an extra
 * <div type="textpart" subtype="book" n="Agis|Cleomenes|Tiberius|Caius">
 * level between the edition and its chapters (chapter numbers restart at 1
 * within each named part, and each part has its own <head> title) - verified
 * by direct inspection, not assumed. `parts` captures this; every other
 * entry has `parts: null` and is imported as a flat chapter sequence
 * (Division id `ch-N`) with no book level, per the importer brief.
 */

export interface PlutarchPart {
  /** the source's own <div subtype="book"> n= value, e.g. "Agis" */
  n: string;
  /** kebab-case, used to build this part's Division id: `book-<slug>` / `book-<slug>-ch-N` */
  slug: string;
  /** verbatim, cleaned <head> text of this part in the Greek witness */
  headGrc: string;
  /** verbatim, cleaned <head> text of this part in the English witness */
  headEng: string;
}

export interface PlutarchWorkEntry {
  /** tlg001..tlg066 */
  tlg: string;
  /** data/plutarch-<slug>-{grc,en} */
  slug: string;
  /** conventional English title (from __cts__.xml <ti:title xml:lang="eng">) - registry commonTitle on the Greek edition */
  engTitle: string;
  /** Greek title (from __cts__.xml edition <ti:label xml:lang="grc">) */
  grcTitle: string;
  /** raw XML filename under scripts/import-plutarch/raw/ (Greek) */
  grcFile: string;
  /** raw XML filename under scripts/import-plutarch/raw/ (English) */
  engFile: string;
  /** Perseus witness id, e.g. "perseus-grc2" / "perseus-grc1" */
  grcWitness: string;
  engWitness: string;
  /** Loeb volume, roman numeral as printed in the CTS <ti:description> (I-XI) */
  volRoman: string;
  /** same, as an integer */
  volNum: number;
  /** Loeb first-publication year for this volume, from the Greek edition's <ti:description> */
  year: number;
  /** same, from the English translation's own <ti:description> (verified equal to `year` for all 66 works) */
  yearEng: number;
  /** null for 64 of the 66 works (flat chapter sequence); the two double lives' book-level parts otherwise - see module doc */
  parts: readonly PlutarchPart[] | null;
}

export const PLUTARCH_WORKS: readonly PlutarchWorkEntry[] = [
  {
    tlg: 'tlg001',
    slug: 'theseus',
    engTitle: 'Theseus',
    grcTitle: 'Θησεύς',
    grcFile: 'tlg0007.tlg001.perseus-grc2.xml',
    engFile: 'tlg0007.tlg001.perseus-eng3.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng3',
    volRoman: 'I',
    volNum: 1,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg002',
    slug: 'romulus',
    engTitle: 'Romulus',
    grcTitle: 'Ῥωμύλος',
    grcFile: 'tlg0007.tlg002.perseus-grc2.xml',
    engFile: 'tlg0007.tlg002.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'I',
    volNum: 1,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg003',
    slug: 'comparison-of-theseus-and-romulus',
    engTitle: 'Comparison of Theseus and Romulus',
    grcTitle: 'Θησέως καὶ Ῥωμύλου σύγκρισις',
    grcFile: 'tlg0007.tlg003.perseus-grc2.xml',
    engFile: 'tlg0007.tlg003.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'I',
    volNum: 1,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg004',
    slug: 'lycurgus',
    engTitle: 'Lycurgus',
    grcTitle: 'Λυκοῦργος',
    grcFile: 'tlg0007.tlg004.perseus-grc2.xml',
    engFile: 'tlg0007.tlg004.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'I',
    volNum: 1,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg005',
    slug: 'numa',
    engTitle: 'Numa',
    grcTitle: 'Νομᾶς',
    grcFile: 'tlg0007.tlg005.perseus-grc2.xml',
    engFile: 'tlg0007.tlg005.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'I',
    volNum: 1,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg006',
    slug: 'comparison-of-lycurgus-and-numa',
    engTitle: 'Comparison of Lycurgus and Numa',
    grcTitle: 'Λυκούργου καὶ Νομᾶ σύγκρισις',
    grcFile: 'tlg0007.tlg006.perseus-grc2.xml',
    engFile: 'tlg0007.tlg006.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'I',
    volNum: 1,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg007',
    slug: 'solon',
    engTitle: 'Solon',
    grcTitle: 'Σόλων',
    grcFile: 'tlg0007.tlg007.perseus-grc2.xml',
    engFile: 'tlg0007.tlg007.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'I',
    volNum: 1,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg008',
    slug: 'publicola',
    engTitle: 'Publicola',
    grcTitle: 'Ποπλικόλας',
    grcFile: 'tlg0007.tlg008.perseus-grc2.xml',
    engFile: 'tlg0007.tlg008.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'I',
    volNum: 1,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg009',
    slug: 'comparison-of-solon-and-publicola',
    engTitle: 'Comparison of Solon and Publicola',
    grcTitle: 'Σόλωνος καὶ Ποπλικόλα σύγκρισις',
    grcFile: 'tlg0007.tlg009.perseus-grc2.xml',
    engFile: 'tlg0007.tlg009.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'I',
    volNum: 1,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg010',
    slug: 'themistocles',
    engTitle: 'Themistocles',
    grcTitle: 'Θεμιστοκλῆς',
    grcFile: 'tlg0007.tlg010.perseus-grc2.xml',
    engFile: 'tlg0007.tlg010.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'II',
    volNum: 2,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg011',
    slug: 'camillus',
    engTitle: 'Camillus',
    grcTitle: 'Κάμιλλος',
    grcFile: 'tlg0007.tlg011.perseus-grc2.xml',
    engFile: 'tlg0007.tlg011.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'II',
    volNum: 2,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg012',
    slug: 'pericles',
    engTitle: 'Pericles',
    grcTitle: 'Περικλῆς',
    grcFile: 'tlg0007.tlg012.perseus-grc2.xml',
    engFile: 'tlg0007.tlg012.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'III',
    volNum: 3,
    year: 1916,
    yearEng: 1916,
    parts: null,
  },
  {
    tlg: 'tlg013',
    slug: 'fabius-maximus',
    engTitle: 'Fabius Maximus',
    grcTitle: 'Φάβιος Μάξιμος',
    grcFile: 'tlg0007.tlg013.perseus-grc2.xml',
    engFile: 'tlg0007.tlg013.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'III',
    volNum: 3,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg014',
    slug: 'comparison-of-pericles-and-fabius-maximus',
    engTitle: 'Comparison of Pericles and Fabius Maximus',
    grcTitle: 'Περικλέους καὶ Φαβίου σύγκρισις',
    grcFile: 'tlg0007.tlg014.perseus-grc2.xml',
    engFile: 'tlg0007.tlg014.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'III',
    volNum: 3,
    year: 1916,
    yearEng: 1916,
    parts: null,
  },
  {
    tlg: 'tlg015',
    slug: 'alcibiades',
    engTitle: 'Alcibiades',
    grcTitle: 'Ἀλκιβιάδης',
    grcFile: 'tlg0007.tlg015.perseus-grc2.xml',
    engFile: 'tlg0007.tlg015.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'IV',
    volNum: 4,
    year: 1916,
    yearEng: 1916,
    parts: null,
  },
  {
    tlg: 'tlg016',
    slug: 'caius-marcius-coriolanus',
    engTitle: 'Caius Marcius Coriolanus',
    grcTitle: 'Γάϊος Μάρκιος',
    grcFile: 'tlg0007.tlg016.perseus-grc2.xml',
    engFile: 'tlg0007.tlg016.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'IV',
    volNum: 4,
    year: 1916,
    yearEng: 1916,
    parts: null,
  },
  {
    tlg: 'tlg017',
    slug: 'comparison-of-alcibiades-and-coriolanus',
    engTitle: 'Comparison of Alcibiades and Coriolanus',
    grcTitle: 'Ἀλκιβιάδου καὶ Κοριολὰνου σύγκρισις',
    grcFile: 'tlg0007.tlg017.perseus-grc2.xml',
    engFile: 'tlg0007.tlg017.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'IV',
    volNum: 4,
    year: 1916,
    yearEng: 1916,
    parts: null,
  },
  {
    tlg: 'tlg018',
    slug: 'timoleon',
    engTitle: 'Timoleon',
    grcTitle: 'Τιμολέων',
    grcFile: 'tlg0007.tlg018.perseus-grc2.xml',
    engFile: 'tlg0007.tlg018.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VI',
    volNum: 6,
    year: 1918,
    yearEng: 1918,
    parts: null,
  },
  {
    tlg: 'tlg019',
    slug: 'aemilius-paulus',
    engTitle: 'Aemilius Paulus',
    grcTitle: 'Αἰμίλιος Παῦλλος',
    grcFile: 'tlg0007.tlg019.perseus-grc2.xml',
    engFile: 'tlg0007.tlg019.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VI',
    volNum: 6,
    year: 1918,
    yearEng: 1918,
    parts: null,
  },
  {
    tlg: 'tlg020',
    slug: 'comparison-of-timoleon-and-aemilius',
    engTitle: 'Comparison of Timoleon and Aemilius',
    grcTitle: 'Σύγκρισις Τιμολέοντος καὶ Αἰμιλίου',
    grcFile: 'tlg0007.tlg020.perseus-grc2.xml',
    engFile: 'tlg0007.tlg020.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VI',
    volNum: 6,
    year: 1918,
    yearEng: 1918,
    parts: null,
  },
  {
    tlg: 'tlg021',
    slug: 'pelopidas',
    engTitle: 'Pelopidas',
    grcTitle: 'Πελοπίδας',
    grcFile: 'tlg0007.tlg021.perseus-grc2.xml',
    engFile: 'tlg0007.tlg021.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'V',
    volNum: 5,
    year: 1917,
    yearEng: 1917,
    parts: null,
  },
  {
    tlg: 'tlg022',
    slug: 'marcellus',
    engTitle: 'Marcellus',
    grcTitle: 'Μάρκελλος',
    grcFile: 'tlg0007.tlg022.perseus-grc2.xml',
    engFile: 'tlg0007.tlg022.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'V',
    volNum: 5,
    year: 1917,
    yearEng: 1917,
    parts: null,
  },
  {
    tlg: 'tlg023',
    slug: 'comparison-of-pelopidas-and-marcellus',
    engTitle: 'Comparison of Pelopidas and Marcellus',
    grcTitle: 'Πελοπίδου καὶ Μαρκέλλου σύγκρισις',
    grcFile: 'tlg0007.tlg023.perseus-grc2.xml',
    engFile: 'tlg0007.tlg023.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'V',
    volNum: 5,
    year: 1917,
    yearEng: 1917,
    parts: null,
  },
  {
    tlg: 'tlg024',
    slug: 'aristides',
    engTitle: 'Aristides',
    grcTitle: 'Ἀριστείδης',
    grcFile: 'tlg0007.tlg024.perseus-grc2.xml',
    engFile: 'tlg0007.tlg024.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'II',
    volNum: 2,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg025',
    slug: 'marcus-cato',
    engTitle: 'Marcus Cato',
    grcTitle: 'Μάρκος Κάτων',
    grcFile: 'tlg0007.tlg025.perseus-grc2.xml',
    engFile: 'tlg0007.tlg025.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'II',
    volNum: 2,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg026',
    slug: 'comparison-of-aristides-and-marcus-cato',
    engTitle: 'Comparison of Aristides and Marcus Cato',
    grcTitle: 'Ἀριστείδου καὶ Κάτωνος σύγκρισις',
    grcFile: 'tlg0007.tlg026.perseus-grc2.xml',
    engFile: 'tlg0007.tlg026.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'II',
    volNum: 2,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg027',
    slug: 'philopoemen',
    engTitle: 'Philopoemen',
    grcTitle: 'Φιλοποίμην',
    grcFile: 'tlg0007.tlg027.perseus-grc2.xml',
    engFile: 'tlg0007.tlg027.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'X',
    volNum: 10,
    year: 1921,
    yearEng: 1921,
    parts: null,
  },
  {
    tlg: 'tlg028',
    slug: 'titus-flamininus',
    engTitle: 'Titus Flamininus',
    grcTitle: 'Τίτος Φλαμινῖνος',
    grcFile: 'tlg0007.tlg028.perseus-grc2.xml',
    engFile: 'tlg0007.tlg028.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'X',
    volNum: 10,
    year: 1921,
    yearEng: 1921,
    parts: null,
  },
  {
    tlg: 'tlg029',
    slug: 'comparison-of-philopoemen-and-titus',
    engTitle: 'Comparison of Philopoemen and Titus',
    grcTitle: 'Φιλοποίμενος καὶ Τίτου σύγκρισις',
    grcFile: 'tlg0007.tlg029.perseus-grc2.xml',
    engFile: 'tlg0007.tlg029.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'X',
    volNum: 10,
    year: 1921,
    yearEng: 1921,
    parts: null,
  },
  {
    tlg: 'tlg030',
    slug: 'pyrrhus',
    engTitle: 'Pyrrhus',
    grcTitle: 'Πύρρος',
    grcFile: 'tlg0007.tlg030.perseus-grc2.xml',
    engFile: 'tlg0007.tlg030.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'IX',
    volNum: 9,
    year: 1920,
    yearEng: 1920,
    parts: null,
  },
  {
    tlg: 'tlg031',
    slug: 'caius-marius',
    engTitle: 'Caius Marius',
    grcTitle: 'Γάιος Μάριος',
    grcFile: 'tlg0007.tlg031.perseus-grc2.xml',
    engFile: 'tlg0007.tlg031.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'IX',
    volNum: 9,
    year: 1920,
    yearEng: 1920,
    parts: null,
  },
  {
    tlg: 'tlg032',
    slug: 'lysander',
    engTitle: 'Lysander',
    grcTitle: 'Λύσανδρος',
    grcFile: 'tlg0007.tlg032.perseus-grc2.xml',
    engFile: 'tlg0007.tlg032.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'IV',
    volNum: 4,
    year: 1916,
    yearEng: 1916,
    parts: null,
  },
  {
    tlg: 'tlg033',
    slug: 'sulla',
    engTitle: 'Sulla',
    grcTitle: 'Σύλλας',
    grcFile: 'tlg0007.tlg033.perseus-grc2.xml',
    engFile: 'tlg0007.tlg033.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'IV',
    volNum: 4,
    year: 1916,
    yearEng: 1916,
    parts: null,
  },
  {
    tlg: 'tlg034',
    slug: 'comparison-of-lysander-and-sulla',
    engTitle: 'Comparison of Lysander and Sulla',
    grcTitle: 'Σύγκρισις Λυσάνδρου καὶ Σύλλα',
    grcFile: 'tlg0007.tlg034.perseus-grc2.xml',
    engFile: 'tlg0007.tlg034.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'IV',
    volNum: 4,
    year: 1916,
    yearEng: 1916,
    parts: null,
  },
  {
    tlg: 'tlg035',
    slug: 'cimon',
    engTitle: 'Cimon',
    grcTitle: 'Κίμων',
    grcFile: 'tlg0007.tlg035.perseus-grc2.xml',
    engFile: 'tlg0007.tlg035.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'II',
    volNum: 2,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg036',
    slug: 'lucullus',
    engTitle: 'Lucullus',
    grcTitle: 'Λούκουλλος',
    grcFile: 'tlg0007.tlg036.perseus-grc2.xml',
    engFile: 'tlg0007.tlg036.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'II',
    volNum: 2,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg037',
    slug: 'comparison-of-lucullus-and-cimon',
    engTitle: 'Comparison of Lucullus and Cimon',
    grcTitle: 'Κίμωνος καὶ Λουκούλλος σύγκρισις',
    grcFile: 'tlg0007.tlg037.perseus-grc2.xml',
    engFile: 'tlg0007.tlg037.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'II',
    volNum: 2,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg038',
    slug: 'nicias',
    engTitle: 'Nicias',
    grcTitle: 'Νικίας',
    grcFile: 'tlg0007.tlg038.perseus-grc2.xml',
    engFile: 'tlg0007.tlg038.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'III',
    volNum: 3,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg039',
    slug: 'crassus',
    engTitle: 'Crassus',
    grcTitle: 'Κράσσος',
    grcFile: 'tlg0007.tlg039.perseus-grc2.xml',
    engFile: 'tlg0007.tlg039.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'III',
    volNum: 3,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg040',
    slug: 'comparison-of-nicias-and-crassus',
    engTitle: 'Comparison of Nicias and Crassus',
    grcTitle: 'Νικίου καὶ Κράσσου σύγκρισις',
    grcFile: 'tlg0007.tlg040.perseus-grc2.xml',
    engFile: 'tlg0007.tlg040.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'III',
    volNum: 3,
    year: 1914,
    yearEng: 1914,
    parts: null,
  },
  {
    tlg: 'tlg041',
    slug: 'eumenes',
    engTitle: 'Eumenes',
    grcTitle: 'Εὐμένης',
    grcFile: 'tlg0007.tlg041.perseus-grc2.xml',
    engFile: 'tlg0007.tlg041.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VIII',
    volNum: 8,
    year: 1919,
    yearEng: 1919,
    parts: null,
  },
  {
    tlg: 'tlg042',
    slug: 'sertorius',
    engTitle: 'Sertorius',
    grcTitle: 'Σερτώριος',
    grcFile: 'tlg0007.tlg042.perseus-grc2.xml',
    engFile: 'tlg0007.tlg042.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VIII',
    volNum: 8,
    year: 1919,
    yearEng: 1919,
    parts: null,
  },
  {
    tlg: 'tlg043',
    slug: 'comparison-of-sertorius-and-eumenes',
    engTitle: 'Comparison of Sertorius and Eumenes',
    grcTitle: 'Σύγκρισις Σερτωρίου καὶ Εὐμένους',
    grcFile: 'tlg0007.tlg043.perseus-grc2.xml',
    engFile: 'tlg0007.tlg043.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VIII',
    volNum: 8,
    year: 1919,
    yearEng: 1919,
    parts: null,
  },
  {
    tlg: 'tlg044',
    slug: 'agesilaus',
    engTitle: 'Agesilaus',
    grcTitle: 'Ἀγησίλαος',
    grcFile: 'tlg0007.tlg044.perseus-grc2.xml',
    engFile: 'tlg0007.tlg044.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'V',
    volNum: 5,
    year: 1917,
    yearEng: 1917,
    parts: null,
  },
  {
    tlg: 'tlg045',
    slug: 'pompey',
    engTitle: 'Pompey',
    grcTitle: 'Πομπήϊος',
    grcFile: 'tlg0007.tlg045.perseus-grc2.xml',
    engFile: 'tlg0007.tlg045.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'V',
    volNum: 5,
    year: 1917,
    yearEng: 1917,
    parts: null,
  },
  {
    tlg: 'tlg046',
    slug: 'comparison-of-agesilaus-and-pompey',
    engTitle: 'Comparison of Agesilaus and Pompey',
    grcTitle: 'Ἀγησιλάου καὶ Πομπηΐου σύγκρισις',
    grcFile: 'tlg0007.tlg046.perseus-grc2.xml',
    engFile: 'tlg0007.tlg046.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'V',
    volNum: 5,
    year: 1917,
    yearEng: 1917,
    parts: null,
  },
  {
    tlg: 'tlg047',
    slug: 'alexander',
    engTitle: 'Alexander',
    grcTitle: 'Ἀλέξανδρος',
    grcFile: 'tlg0007.tlg047.perseus-grc2.xml',
    engFile: 'tlg0007.tlg047.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VII',
    volNum: 7,
    year: 1919,
    yearEng: 1919,
    parts: null,
  },
  {
    tlg: 'tlg048',
    slug: 'caesar',
    engTitle: 'Caesar',
    grcTitle: 'Καῖσαρ',
    grcFile: 'tlg0007.tlg048.perseus-grc2.xml',
    engFile: 'tlg0007.tlg048.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VII',
    volNum: 7,
    year: 1919,
    yearEng: 1919,
    parts: null,
  },
  {
    tlg: 'tlg049',
    slug: 'phocion',
    engTitle: 'Phocion',
    grcTitle: 'Φωκίων',
    grcFile: 'tlg0007.tlg049.perseus-grc2.xml',
    engFile: 'tlg0007.tlg049.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VIII',
    volNum: 8,
    year: 1919,
    yearEng: 1919,
    parts: null,
  },
  {
    tlg: 'tlg050',
    slug: 'cato-the-younger',
    engTitle: 'Cato the Younger',
    grcTitle: 'Κάτων',
    grcFile: 'tlg0007.tlg050.perseus-grc2.xml',
    engFile: 'tlg0007.tlg050.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VIII',
    volNum: 8,
    year: 1919,
    yearEng: 1919,
    parts: null,
  },
  {
    tlg: 'tlg051',
    slug: 'agis-and-cleomenes',
    engTitle: 'Agis and Cleomenes',
    grcTitle: 'Ἄγις καὶ Κλεομένης',
    grcFile: 'tlg0007.tlg051.perseus-grc1.xml',
    engFile: 'tlg0007.tlg051.perseus-eng1.xml',
    grcWitness: 'perseus-grc1',
    engWitness: 'perseus-eng1',
    volRoman: 'X',
    volNum: 10,
    year: 1921,
    yearEng: 1921,
    parts: [
      { n: 'Agis', slug: 'agis', headGrc: 'Ἄγις', headEng: 'AGIS' },
      { n: 'Cleomenes', slug: 'cleomenes', headGrc: 'Κλεομένης', headEng: 'CLEOMENES' },
    ],
  },
  {
    tlg: 'tlg052',
    slug: 'tiberius-and-caius-gracchus',
    engTitle: 'Tiberius and Caius Gracchus',
    grcTitle: 'Tιβέριος καὶ Γάιος Γράκχοι',
    grcFile: 'tlg0007.tlg052.perseus-grc1.xml',
    engFile: 'tlg0007.tlg052.perseus-eng1.xml',
    grcWitness: 'perseus-grc1',
    engWitness: 'perseus-eng1',
    volRoman: 'X',
    volNum: 10,
    year: 1921,
    yearEng: 1921,
    parts: [
      { n: 'Tiberius', slug: 'tiberius', headGrc: 'Τιβέριος Γράγχος', headEng: 'TIBERIUS GRACCHUS' },
      { n: 'Caius', slug: 'caius', headGrc: 'Γάϊος Γράγχος', headEng: 'CAIUS GRACCHUS' },
    ],
  },
  {
    tlg: 'tlg053',
    slug: 'comparison-of-agis-and-cleomenes-and-the-gracchi',
    engTitle: 'Comparison of Agis and Cleomenes and the Gracchi',
    grcTitle: 'Σύγκρισις Ἄγιδος καὶ Κλεομένους καὶ τῶν Γράκχων',
    grcFile: 'tlg0007.tlg053.perseus-grc2.xml',
    engFile: 'tlg0007.tlg053.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'X',
    volNum: 10,
    year: 1921,
    yearEng: 1921,
    parts: null,
  },
  {
    tlg: 'tlg054',
    slug: 'demosthenes',
    engTitle: 'Demosthenes',
    grcTitle: 'Δημοσθένης',
    grcFile: 'tlg0007.tlg054.perseus-grc2.xml',
    engFile: 'tlg0007.tlg054.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VII',
    volNum: 7,
    year: 1919,
    yearEng: 1919,
    parts: null,
  },
  {
    tlg: 'tlg055',
    slug: 'cicero',
    engTitle: 'Cicero',
    grcTitle: 'Κικέρων',
    grcFile: 'tlg0007.tlg055.perseus-grc2.xml',
    engFile: 'tlg0007.tlg055.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VII',
    volNum: 7,
    year: 1919,
    yearEng: 1919,
    parts: null,
  },
  {
    tlg: 'tlg056',
    slug: 'comparison-of-demosthenes-and-cicero',
    engTitle: 'Comparison of Demosthenes and Cicero',
    grcTitle: 'Σύγκρισις Δημοσθένους καὶ Κικέρωνος',
    grcFile: 'tlg0007.tlg056.perseus-grc2.xml',
    engFile: 'tlg0007.tlg056.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VII',
    volNum: 7,
    year: 1919,
    yearEng: 1919,
    parts: null,
  },
  {
    tlg: 'tlg057',
    slug: 'demetrius',
    engTitle: 'Demetrius',
    grcTitle: 'Δημήτριος',
    grcFile: 'tlg0007.tlg057.perseus-grc2.xml',
    engFile: 'tlg0007.tlg057.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'IX',
    volNum: 9,
    year: 1920,
    yearEng: 1920,
    parts: null,
  },
  {
    tlg: 'tlg058',
    slug: 'antony',
    engTitle: 'Antony',
    grcTitle: 'Ἀντώνιος',
    grcFile: 'tlg0007.tlg058.perseus-grc2.xml',
    engFile: 'tlg0007.tlg058.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'IX',
    volNum: 9,
    year: 1920,
    yearEng: 1920,
    parts: null,
  },
  {
    tlg: 'tlg059',
    slug: 'comparison-of-demetrius-and-antony',
    engTitle: 'Comparison of Demetrius and Antony',
    grcTitle: 'Σύγκρισις Δημητρίου καὶ Ἀντωνίου',
    grcFile: 'tlg0007.tlg059.perseus-grc2.xml',
    engFile: 'tlg0007.tlg059.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'IX',
    volNum: 9,
    year: 1920,
    yearEng: 1920,
    parts: null,
  },
  {
    tlg: 'tlg060',
    slug: 'dion',
    engTitle: 'Dion',
    grcTitle: 'Δίων',
    grcFile: 'tlg0007.tlg060.perseus-grc2.xml',
    engFile: 'tlg0007.tlg060.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VI',
    volNum: 6,
    year: 1918,
    yearEng: 1918,
    parts: null,
  },
  {
    tlg: 'tlg061',
    slug: 'brutus',
    engTitle: 'Brutus',
    grcTitle: 'Βροῦτος',
    grcFile: 'tlg0007.tlg061.perseus-grc2.xml',
    engFile: 'tlg0007.tlg061.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VI',
    volNum: 6,
    year: 1918,
    yearEng: 1918,
    parts: null,
  },
  {
    tlg: 'tlg062',
    slug: 'comparison-of-dion-and-brutus',
    engTitle: 'Comparison of Dion and Brutus',
    grcTitle: 'Σύγκρισις Δίωνος καὶ Βρούτου',
    grcFile: 'tlg0007.tlg062.perseus-grc2.xml',
    engFile: 'tlg0007.tlg062.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'VI',
    volNum: 6,
    year: 1918,
    yearEng: 1918,
    parts: null,
  },
  {
    tlg: 'tlg063',
    slug: 'aratus',
    engTitle: 'Aratus',
    grcTitle: 'Ἄρατος',
    grcFile: 'tlg0007.tlg063.perseus-grc2.xml',
    engFile: 'tlg0007.tlg063.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'XI',
    volNum: 11,
    year: 1926,
    yearEng: 1926,
    parts: null,
  },
  {
    tlg: 'tlg064',
    slug: 'artaxerxes',
    engTitle: 'Artaxerxes',
    grcTitle: 'Ἀρταξέρξης',
    grcFile: 'tlg0007.tlg064.perseus-grc2.xml',
    engFile: 'tlg0007.tlg064.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'XI',
    volNum: 11,
    year: 1926,
    yearEng: 1926,
    parts: null,
  },
  {
    tlg: 'tlg065',
    slug: 'galba',
    engTitle: 'Galba',
    grcTitle: 'Γάλβας',
    grcFile: 'tlg0007.tlg065.perseus-grc2.xml',
    engFile: 'tlg0007.tlg065.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'XI',
    volNum: 11,
    year: 1926,
    yearEng: 1926,
    parts: null,
  },
  {
    tlg: 'tlg066',
    slug: 'otho',
    engTitle: 'Otho',
    grcTitle: 'Ὄθων',
    grcFile: 'tlg0007.tlg066.perseus-grc2.xml',
    engFile: 'tlg0007.tlg066.perseus-eng2.xml',
    grcWitness: 'perseus-grc2',
    engWitness: 'perseus-eng2',
    volRoman: 'XI',
    volNum: 11,
    year: 1926,
    yearEng: 1926,
    parts: null,
  },
];
