/**
 * Per-dialogue configuration table for 28 Plato imports: the five from batch A
 * (Symposium, Phaedrus, Protagoras, Gorgias, Timaeus) plus 23 from batch B
 * (Cratylus, Theaetetus, Sophist, Statesman, Parmenides, Philebus, Alcibiades I/II,
 * Hipparchus, Lovers, Theages, Charmides, Laches, Lysis, Euthydemus, Greater/Lesser
 * Hippias, Menexenus, Cleitophon, Critias, Minos, Epinomis, Letters).
 * CTS URNs and witness ids per the import spec; bibliographic fields
 * (editor/translator/imprint/volume/date) transcribed verbatim from each raw
 * file's own <sourceDesc> (not looked up externally), so they are guaranteed
 * to match what this app actually bundles.
 */

export interface DialogueMeta {
  slug: 'symposium' | 'phaedrus' | 'protagoras' | 'gorgias' | 'timaeus' | 'cratylus' | 'theaetetus' | 'sophist' | 'statesman' | 'parmenides' | 'philebus' | 'alcibiades-1' | 'alcibiades-2' | 'hipparchus' | 'lovers' | 'theages' | 'charmides' | 'laches' | 'lysis' | 'euthydemus' | 'greater-hippias' | 'lesser-hippias' | 'menexenus' | 'cleitophon' | 'critias' | 'minos' | 'epinomis' | 'letters';
  tlg: string; // e.g. 'tlg011'
  greekTitle: string;
  englishTitle: string;
  /** expected Stephanus page range, inclusive — independently verified against the raw XML before writing this table */
  firstPage: number;
  lastPage: number;
  /** Burnet OCT (Platonis Opera) volume + date, from the Greek witness's own <sourceDesc> */
  burnetVolume: string;
  burnetDate: string;
  burnetArchiveUrl: string;
  /** English translator(s), exactly as the English witness's own <sourceDesc> lists them (role="translator" editor(s), in source order) */
  translators: string[];
  /** "Plato in Twelve Volumes" (Loeb Classical Library) internal volume number + printing date, from the English witness's own <sourceDesc> */
  loebVolume: string;
  loebDate: string;
  loebArchiveUrl: string;
}

export const DIALOGUES: DialogueMeta[] = [
  {
    slug: 'symposium',
    tlg: 'tlg011',
    greekTitle: 'Συμπόσιον',
    englishTitle: 'Symposium',
    firstPage: 172,
    lastPage: 223,
    burnetVolume: '2',
    burnetDate: '1910',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb02platuoft',
    translators: ['Walter Rangeley Maitland Lamb'],
    loebVolume: '3',
    loebDate: '1925',
    loebArchiveUrl: 'https://archive.org/details/in.ernet.dli.2015.183496',
  },
  {
    slug: 'phaedrus',
    tlg: 'tlg012',
    greekTitle: 'Φαῖδρος',
    englishTitle: 'Phaedrus',
    firstPage: 227,
    lastPage: 279,
    burnetVolume: '2',
    burnetDate: '1910',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb02platuoft',
    translators: ['Harold North Fowler', 'Walter Rangeley Maitland Lamb'],
    loebVolume: '1',
    loebDate: '1914',
    loebArchiveUrl: 'https://archive.org/details/in.ernet.dli.2015.102296',
  },
  {
    slug: 'protagoras',
    tlg: 'tlg022',
    greekTitle: 'Πρωταγόρας',
    englishTitle: 'Protagoras',
    firstPage: 309,
    lastPage: 362,
    burnetVolume: '3',
    burnetDate: '1903',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb03platuoft',
    translators: ['Walter Rangeley Maitland Lamb'],
    loebVolume: '2',
    loebDate: '1924',
    loebArchiveUrl: 'https://archive.org/details/L165PlatoIILachesProtagorasMenoEuthydemus',
  },
  {
    slug: 'gorgias',
    tlg: 'tlg023',
    greekTitle: 'Γοργίας',
    englishTitle: 'Gorgias',
    firstPage: 447,
    lastPage: 527,
    burnetVolume: '3',
    burnetDate: '1903',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb03platuoft',
    translators: ['Walter Rangeley Maitland Lamb'],
    loebVolume: '3',
    loebDate: '1925',
    loebArchiveUrl: 'https://archive.org/details/in.ernet.dli.2015.183496',
  },
  {
    slug: 'timaeus',
    tlg: 'tlg031',
    greekTitle: 'Τίμαιος',
    englishTitle: 'Timaeus',
    firstPage: 17,
    lastPage: 92,
    burnetVolume: '4',
    burnetDate: '1905',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb04platuoft',
    translators: ['Robert Gregg Bury'],
    loebVolume: '9',
    loebDate: '1929',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0009',
  },
  {
    slug: 'cratylus',
    tlg: 'tlg005',
    greekTitle: 'Κρατύλος',
    englishTitle: 'Cratylus',
    firstPage: 383,
    lastPage: 440,
    burnetVolume: '1',
    burnetDate: '1905',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb01platuoft',
    translators: ['Harold North Fowler', 'W.R.M. Lamb'],
    loebVolume: '4',
    loebDate: '1926',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0004',
  },
  {
    slug: 'theaetetus',
    tlg: 'tlg006',
    greekTitle: 'Θεαίτητος',
    englishTitle: 'Theaetetus',
    firstPage: 142,
    lastPage: 210,
    burnetVolume: '1',
    burnetDate: '1905',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb01platuoft',
    translators: ['Harold North Fowler'],
    loebVolume: '7',
    loebDate: '1921',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0007',
  },
  {
    slug: 'sophist',
    tlg: 'tlg007',
    greekTitle: 'Σοφιστής',
    englishTitle: 'Sophist',
    firstPage: 216,
    lastPage: 268,
    burnetVolume: '1',
    burnetDate: '1905',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb01platuoft',
    translators: ['Harold North Fowler'],
    loebVolume: '7',
    loebDate: '1921',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0007',
  },
  {
    slug: 'statesman',
    tlg: 'tlg008',
    greekTitle: 'Πολιτικός',
    englishTitle: 'Statesman',
    firstPage: 257,
    lastPage: 311,
    burnetVolume: '1',
    burnetDate: '1905',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb01platuoft',
    translators: ['Harold North Fowler'],
    loebVolume: '8',
    loebDate: '1925',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0008',
  },
  {
    slug: 'parmenides',
    tlg: 'tlg009',
    greekTitle: 'Παρμενίδης',
    englishTitle: 'Parmenides',
    firstPage: 126,
    lastPage: 166,
    burnetVolume: '2',
    burnetDate: '1910',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb02platuoft',
    translators: ['Harold North Fowler', 'W.R.M. Lamb'],
    loebVolume: '4',
    loebDate: '1926',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0004',
  },
  {
    slug: 'philebus',
    tlg: 'tlg010',
    greekTitle: 'Φίληβος',
    englishTitle: 'Philebus',
    firstPage: 11,
    lastPage: 67,
    burnetVolume: '2',
    burnetDate: '1910',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb02platuoft',
    translators: ['Harold North Fowler'],
    loebVolume: '8',
    loebDate: '1925',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0008',
  },
  {
    slug: 'alcibiades-1',
    tlg: 'tlg013',
    greekTitle: 'Ἀλκιβιάδης αʹ',
    englishTitle: 'Alcibiades I',
    firstPage: 103,
    lastPage: 135,
    burnetVolume: '2',
    burnetDate: '1910',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb02platuoft',
    translators: ['W.R.M. Lamb'],
    loebVolume: '12',
    loebDate: '1927',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0012',
  },
  {
    slug: 'alcibiades-2',
    tlg: 'tlg014',
    greekTitle: 'Ἀλκιβιάδης βʹ',
    englishTitle: 'Alcibiades II',
    firstPage: 138,
    lastPage: 151,
    burnetVolume: '2',
    burnetDate: '1910',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb02platuoft',
    translators: ['W.R.M. Lamb'],
    loebVolume: '12',
    loebDate: '1927',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0012',
  },
  {
    slug: 'hipparchus',
    tlg: 'tlg015',
    greekTitle: 'Ἵππαρχος',
    englishTitle: 'Hipparchus',
    firstPage: 225,
    lastPage: 232,
    burnetVolume: '2',
    burnetDate: '1910',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb02platuoft',
    translators: ['W.R.M. Lamb'],
    loebVolume: '12',
    loebDate: '1927',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0012',
  },
  {
    slug: 'lovers',
    tlg: 'tlg016',
    greekTitle: 'Ἐρασταί',
    englishTitle: 'Lovers (Erastai)',
    firstPage: 132,
    lastPage: 139,
    burnetVolume: '2',
    burnetDate: '1910',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb02platuoft',
    translators: ['W.R.M. Lamb'],
    loebVolume: '12',
    loebDate: '1927',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0012',
  },
  {
    slug: 'theages',
    tlg: 'tlg017',
    greekTitle: 'Θεάγης',
    englishTitle: 'Theages',
    firstPage: 121,
    lastPage: 131,
    burnetVolume: '3',
    burnetDate: '1903',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb03platuoft',
    translators: ['W.R.M. Lamb'],
    loebVolume: '12',
    loebDate: '1927',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0012',
  },
  {
    slug: 'charmides',
    tlg: 'tlg018',
    greekTitle: 'Χαρμίδης',
    englishTitle: 'Charmides',
    firstPage: 153,
    lastPage: 176,
    burnetVolume: '3',
    burnetDate: '1913',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb03platuoft',
    translators: ['W.R.M. Lamb'],
    loebVolume: '12',
    loebDate: '1927',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0012',
  },
  {
    slug: 'laches',
    tlg: 'tlg019',
    greekTitle: 'Λάχης',
    englishTitle: 'Laches',
    firstPage: 178,
    lastPage: 201,
    burnetVolume: '3',
    burnetDate: '1903',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb03platuoft',
    translators: ['W.R.M. Lamb'],
    loebVolume: '2',
    loebDate: '1924',
    loebArchiveUrl: 'https://archive.org/details/L165PlatoIILachesProtagorasMenoEuthydemus',
  },
  {
    slug: 'lysis',
    tlg: 'tlg020',
    greekTitle: 'Λύσις',
    englishTitle: 'Lysis',
    firstPage: 203,
    lastPage: 223,
    burnetVolume: '3',
    burnetDate: '1903',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb03platuoft',
    translators: ['W.R.M. Lamb'],
    loebVolume: '3',
    loebDate: '1925',
    loebArchiveUrl: 'https://archive.org/details/in.ernet.dli.2015.183496',
  },
  {
    slug: 'euthydemus',
    tlg: 'tlg021',
    greekTitle: 'Εὐθύδημος',
    englishTitle: 'Euthydemus',
    firstPage: 271,
    lastPage: 307,
    burnetVolume: '3',
    burnetDate: '1903',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb03platuoft',
    translators: ['W.R.M. Lamb'],
    loebVolume: '2',
    loebDate: '1924',
    loebArchiveUrl: 'https://archive.org/details/L165PlatoIILachesProtagorasMenoEuthydemus',
  },
  {
    slug: 'greater-hippias',
    tlg: 'tlg025',
    greekTitle: 'Ἱππίας μείζων',
    englishTitle: 'Greater Hippias',
    firstPage: 281,
    lastPage: 304,
    burnetVolume: '3',
    burnetDate: '1903',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb03platuoft',
    translators: ['Harold North Fowler', 'W.R.M. Lamb'],
    loebVolume: '4',
    loebDate: '1926',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0004',
  },
  {
    slug: 'lesser-hippias',
    tlg: 'tlg026',
    greekTitle: 'Ἱππίας ἐλάττων',
    englishTitle: 'Lesser Hippias',
    firstPage: 363,
    lastPage: 376,
    burnetVolume: '3',
    burnetDate: '1903',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb03platuoft',
    translators: ['Harold North Fowler', 'W.R.M. Lamb'],
    loebVolume: '4',
    loebDate: '1926',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0004',
  },
  {
    slug: 'menexenus',
    tlg: 'tlg028',
    greekTitle: 'Μενέξενος',
    englishTitle: 'Menexenus',
    firstPage: 234,
    lastPage: 249,
    burnetVolume: '3',
    burnetDate: '1903',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb03platuoft',
    translators: ['R.G. Bury'],
    loebVolume: '9',
    loebDate: '1929',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0009',
  },
  {
    slug: 'cleitophon',
    tlg: 'tlg029',
    greekTitle: 'Κλειτοφῶν',
    englishTitle: 'Cleitophon',
    firstPage: 406,
    lastPage: 410,
    burnetVolume: '4',
    burnetDate: '1905',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb04platuoft',
    translators: ['R.G. Bury'],
    loebVolume: '9',
    loebDate: '1929',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0009',
  },
  {
    slug: 'critias',
    tlg: 'tlg032',
    greekTitle: 'Κριτίας',
    englishTitle: 'Critias',
    firstPage: 106,
    lastPage: 121,
    burnetVolume: '4',
    burnetDate: '1905',
    burnetArchiveUrl: 'https://archive.org/details/operarecognovitb04platuoft',
    translators: ['R.G. Bury'],
    loebVolume: '9',
    loebDate: '1929',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0009',
  },
  {
    slug: 'minos',
    tlg: 'tlg033',
    greekTitle: 'Μίνως',
    englishTitle: 'Minos',
    firstPage: 313,
    lastPage: 321,
    burnetVolume: '5',
    burnetDate: '1914',
    burnetArchiveUrl: 'https://archive.org/details/p1platonisopera05platuoft',
    translators: ['W.R.M. Lamb'],
    loebVolume: '12',
    loebDate: '1927',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0012',
  },
  {
    slug: 'epinomis',
    tlg: 'tlg035',
    greekTitle: 'Ἐπινομίς',
    englishTitle: 'Epinomis',
    firstPage: 973,
    lastPage: 992,
    burnetVolume: '5',
    burnetDate: '1914',
    burnetArchiveUrl: 'https://archive.org/details/p2operarecognovitb05platuoft',
    translators: ['W.R.M. Lamb'],
    loebVolume: '12',
    loebDate: '1927',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0012',
  },
  {
    slug: 'letters',
    tlg: 'tlg036',
    greekTitle: 'Ἐπιστολαί',
    englishTitle: 'Letters (Epistles)',
    firstPage: 309,
    lastPage: 363,
    burnetVolume: '5',
    burnetDate: '1914',
    burnetArchiveUrl: 'https://archive.org/details/p2operarecognovitb05platuoft',
    translators: ['R.G. Bury'],
    loebVolume: '9',
    loebDate: '1929',
    loebArchiveUrl: 'https://archive.org/details/b2900049x_0009',
  },
];

export function dialogueMeta(slug: DialogueMeta['slug']): DialogueMeta {
  const d = DIALOGUES.find((x) => x.slug === slug);
  if (!d) throw new Error(`no DialogueMeta for slug ${slug}`);
  return d;
}
