import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { WORKS, SKIPPED_WORKS } from '../import-aristotle-rest-shared/workTable.ts';
import type { Division, GenericWork } from '../import-aristotle-rest-shared/genericTypes.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, '..', '..');
const DATA_ROOT = join(REPO_ROOT, 'data');

function countLeaf(divs: Division[]): number {
  let n = 0;
  for (const d of divs) {
    if (d.children.length === 0) n += 1;
    else n += countLeaf(d.children);
  }
  return n;
}

const rows: string[] = [];
rows.push('# WORKS.md - the "rest of Aristotle" Greek importer');
rows.push('');
rows.push('Generated by scripts/import-aristotle-rest/_gen_works_md.ts from the live workTable.ts + the actual imported data/<workId>/work.json files (not hand-typed) - re-run it after any table/importer change to keep this current.');
rows.push('');
rows.push('| workId | tlg | source/witness | edition | books | chapters | Bekker span | authentic/pseudo |');
rows.push('|---|---|---|---|---|---|---|---|');

for (const entry of WORKS) {
  const work = JSON.parse(readFileSync(join(DATA_ROOT, entry.workId, 'work.json'), 'utf8')) as GenericWork;
  const anomalies = JSON.parse(readFileSync(join(DATA_ROOT, entry.workId, 'anomalies.json'), 'utf8')) as { where: string; note: string }[];
  const books = entry.expectedBooks !== null ? work.divisions.length : null;
  const chapters = countLeaf(work.divisions);
  const spanA = anomalies.find((a) => a.note.includes('whole work') && a.note.includes('No Bekker'));
  const hasSpan = !spanA;
  let span = '—';
  if (hasSpan) {
    const marks: string[] = [];
    const walk = (ds: Division[]) => {
      for (const d of ds) {
        if (d.ref) marks.push(d.ref);
        walk(d.children);
      }
    };
    walk(work.divisions);
    if (marks.length) {
      const first = marks[0]!.split('–')[0]!;
      const last = marks[marks.length - 1]!.split('–').pop()!;
      span = first === last ? first : `${first}–${last}`;
    }
  }
  rows.push(
    `| ${entry.workId} | ${entry.tlg} | ${entry.source}/${entry.witness} | ${entry.editor} (${entry.date}) | ${books ?? '—'} | ${chapters} | ${span} | ${entry.authenticity} |`,
  );
}

rows.push('');
rows.push('## Skipped');
rows.push('');
for (const s of SKIPPED_WORKS) {
  rows.push(`- **${s.workId}**: ${s.reason}`);
}
rows.push('');

writeFileSync(join(REPO_ROOT, 'scripts', 'import-aristotle-rest-shared', 'WORKS.md'), rows.join('\n'), 'utf8');
process.stdout.write('wrote scripts/import-aristotle-rest-shared/WORKS.md\n');
