/**
 * Structural mirror of the generic-work content types in
 * `src/library/types.ts`, used internally by this importer/validator.
 * Each `data/<workId>/types.ts` output is a generated byte-identical copy
 * (see typesTemplate.ts) so each work directory stays self-contained.
 */

/** Mirrors src/library/types.ts#PassageFigure (image variant only is used here). */
export interface PassageFigure {
  image?: string;
  imageWidth?: number;
  imageHeight?: number;
  alt?: string;
  source: string;
  note?: string;
}

export interface Passage {
  n: string;
  text: string;
  ref: string | null;
  anomaly?: string;
  /** a real printed diagram (Mechanica only so far; see diagrams/aristotle.ts) */
  figure?: PassageFigure;
}

export interface Division {
  id: string;
  number: string | null;
  ref: string | null;
  sourceHeading: string | null;
  editorialTitle: string | null;
  children: Division[];
  passages: Passage[];
}

export interface GenericWork {
  workId: string;
  language: 'grc';
  divisions: Division[];
}

export interface WorkAboutSection {
  heading: string;
  paragraphs: string[];
}

export interface WorkAbout {
  workId: string;
  title: string;
  author: string;
  language: 'grc';
  edition?: string;
  editor?: string;
  translator?: string;
  provenance: string;
  license: string;
  sections?: WorkAboutSection[];
}

export interface Anomaly {
  where: string;
  note: string;
}
