/**
 * The ground-truth table for the "rest of Aristotle" Greek importer: every
 * work's source file/witness, edition metadata (as each file's OWN
 * `<sourceDesc>` states it - verified by direct inspection of every raw file
 * before this table was written, not assumed from the task brief), its
 * structural `shape` (see shapes.ts), and the exact division counts this
 * importer independently re-derives on every run as a redundant sanity gate
 * (also independently verified by direct inspection - see
 * scripts/import-aristotle-rest-shared/WORKS.md for the full per-work
 * account of how each count was established).
 *
 * --- Corpus-wide bibliographic notes -----------------------------------
 * Every work below is First1KGreek (`urn:cts:greekLit:tlg0086.tlgNNN.1st1K-
 * grcN`) unless `source` says "perseus" (Perseus/OGL canonical-greekLit,
 * `...perseus-grc2`) or "digicorpus" (Poetics only, `...digicorpus-grc2`).
 *
 * De Mundo (Περὶ κόσμου) is NOT in this table: it does not exist under ANY
 * tlg number in either the First1KGreek or the Perseus/OGL canonical-greekLit
 * repository for Aristotle (tlg0086) - confirmed by listing both
 * repositories' full tlg0086 directory contents (First1KGreek has tlg001-008,
 * 011-024,026,027,030-032,034,036,037,039-044,046-048,052,054; Perseus has
 * only tlg003,009,010,025,029,034,035,038,045) and by fetching every
 * candidate `__cts__.xml`: none is titled "De mundo"/"Περὶ κόσμου". (tlg010,
 * which might look like a plausible guess, is Perseus's Nicomachean Ethics,
 * already bundled elsewhere in this app.) Skipped per the task brief's own
 * instruction for this case; see WORKS.md.
 *
 * De Generatione et Corruptione uses the tlg013.1st1K-grc2 witness (Carl
 * Prantl, Teubner 1881) rather than grc1 (E. S. Forster's Loeb, 1955),
 * deliberately: grc2 is the SAME Prantl edition (and the same Teubner volume,
 * "Aristoteles de coelo et de generatione et corruptione") already used here
 * for De Caelo (tlg005) - a single coherent 19th-century public-domain
 * critical text across both works, rather than mixing a 19th-century Teubner
 * text for one and a 1955 Loeb text (with its own, later apparatus) for its
 * traditional companion volume.
 *
 * Poetics uses tlg034.digicorpus-grc2 (Bekker 1837, per the task brief's
 * preference for the cleaner PD edition), NOT tlg034.perseus-grc2 (Rudolf
 * Kassel's 1965 critical edition) - digicorpus-grc2 was fetched and its
 * structure verified to parse correctly (chapter/subchapter nesting,
 * identical in fact to perseus-grc2's own div structure - both digitisations
 * share the same CTS citation scheme), so no fallback was needed. It carries
 * no inline Bekker citations of its own (verified: neither `<note
 * type="marginal">` nor a Bekker `<milestone>` appears anywhere in the file),
 * unlike perseus-grc2 - Division.ref is therefore null throughout for this
 * work, logged as a single work-level anomaly rather than guessed at.
 *
 * De Melisso, Xenophane, Gorgia (tlg047): this file's OWN Greek title, in its
 * <teiHeader><titleStmt> - not just the CTS catalog's <ti:description>, cross-
 * checked - is "Περὶ Ξενοφάνους, περὶ Ζήνωνος, περὶ Γοργίου" ("On Xenophanes,
 * on Zeno, on Gorgias"), and its own three-part division is literally
 * labelled `part n="Xenoph"`, `part n="Zenon"`, `part n="Georg"` - i.e. this
 * particular Bekker-volume-6 transcription frames the work's middle part as
 * being about ZENO, not Melissus, diverging from the work's usual modern
 * title "De Melisso, Xenophane, Gorgia" (under which this table still lists
 * it, matching the task brief and the rest of the scholarly tradition). Both
 * facts are preserved and disclosed - see about.json.
 *
 * De Spiritu (tlg043): this file's own `<sourceDesc>` cites "Aristotelis De
 * animalium motione et De animalium incessu. Jaeger, Werner, editor. Leipzig:
 * Teubner, 1913" - i.e. the SAME volume-title metadata as tlg015 (De
 * Incessu Animalium) and tlg021 (De Motu Animalium), which is almost
 * certainly a copy/paste error in First1KGreek's own cataloguing (that 1913
 * Teubner volume does not contain De Spiritu). The editor name "Werner
 * Jaeger" and the year 1913 are plausible on their own (Jaeger did publish on
 * the pseudo-Aristotelian De Spiritu around this period) but the exact title
 * cited cannot be corroborated from this file alone, so about.json quotes the
 * source's own (evidently mistaken) citation VERBATIM rather than silently
 * substituting a "corrected" one, and flags the discrepancy explicitly - the
 * "bibliographic gotcha" the task brief asked every file to be checked for.
 */

export type Shape =
  | { kind: 'flat-chapter'; chapterSubtype: string }
  | { kind: 'flat-paragraph'; wrapperSubtype: string }
  | { kind: 'book-chapter'; bookSubtype: string; chapterSubtype: string }
  | { kind: 'book-chapter-filtered'; filterSubtype: string; filterN: string; bookSubtype: string; chapterSubtype: string }
  | { kind: 'book-page'; bookSubtype: string; pageSubtype: string }
  /** Mechanica only: the source's `chapter` divs are the traditional
   *  numbered Problems (n="0" = the unnumbered preface), each holding its own
   *  restarting `section` numbering -> `preface`/`preface-ch-M` and
   *  `problem-N`/`problem-N-ch-M` (globally unique ids). */
  | { kind: 'problem-section'; problemSubtype: string; sectionSubtype: string };

export type Authenticity = 'authentic' | 'disputed' | 'pseudo';

export interface WorkEntry {
  workId: string;
  tlg: string;
  source: 'first1k' | 'perseus' | 'digicorpus';
  witness: string;
  file: string;
  /** Greek title, from the file's own teiHeader when present, else the CTS catalog */
  titleGrc: string;
  /** conventional Latin/English title used for the workId and about.json heading */
  titleConventional: string;
  editor: string;
  edition: string;
  pubPlace: string;
  publisher: string;
  date: string;
  authenticity: Authenticity;
  /** true: an English translation for this exact workId is being imported concurrently
   *  (data/<workId-without-grc>-en) by a separate task; false: not in that task's scope,
   *  englishNote gives the "why not" boilerplate for about.json */
  englishBundledConcurrently: boolean;
  englishNote?: string;
  shape: Shape;
  /** exact division counts this importer independently re-derives, as a redundant
   *  sanity gate (see the module doc comment) */
  expectedBooks: number | null;
  expectedChapters: number;
  bibliographicNote?: string;
  /** true only for de-partibus-animalium-grc - see teiWalker.ts#WalkOptions.
   *  Every other work keeps this importer's default policy: a non-citation
   *  <note> is discarded entirely (tag and content). */
  keepBareNotes?: boolean;
}

const MINOR_OPUSCULA_NOTE =
  'No English translation is bundled: the only public-domain English translation (Loveday/Forster/Dowdall, 1913, in the Oxford "Works of Aristotle" minor-opuscula volumes) exists today only as unproofread OCR of a scanned printing, which this library does not ship as reading text; a proofread source may be added later.';

export const WORKS: readonly WorkEntry[] = [
  {
    workId: 'prior-analytics-grc',
    tlg: 'tlg001',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg001.1st1K-grc1.xml',
    titleGrc: 'Ἀναλυτικὰ πρότερα',
    titleConventional: 'Prior Analytics',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 1 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'book-chapter-filtered', filterSubtype: 'book', filterN: 'priora', bookSubtype: 'part', chapterSubtype: 'chapter' },
    expectedBooks: 2,
    expectedChapters: 73,
    bibliographicNote:
      'This F1K file (tlg0086.tlg001) actually transmits BOTH Prior Analytics AND Posterior Analytics as one continuous Bekker volume-1 text (`book n="priora"` then `book n="posteriora"`), matching how Bekker\'s own 1837 print edition bound them together; Posterior Analytics is already imported elsewhere in this app (data/posterior-analytics-grc) and is untouched by this importer - only `book n="priora"` is read here, per the task brief\'s own instruction: its two `part n="1"/"2"` children map onto this work\'s traditional Book 1 (46 chapters) / Book 2 (27 chapters).',
  },
  {
    workId: 'topics-grc',
    tlg: 'tlg044',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg044.1st1K-grc1.xml',
    titleGrc: 'Τοπικά',
    titleConventional: 'Topics',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 1 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'book-chapter', bookSubtype: 'book', chapterSubtype: 'chapter' },
    expectedBooks: 8,
    expectedChapters: 83,
  },
  {
    workId: 'sophistical-refutations-grc',
    tlg: 'tlg040',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg040.1st1K-grc1.xml',
    titleGrc: 'Περὶ σοφιστικῶν ἐλέγχων',
    titleConventional: 'Sophistical Refutations',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 1 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 33,
    bibliographicNote:
      'Chapter 1\'s very first <p> is the literal three-word title "ΠΕΡΙ ΣΟΦΙΣΤΙΚΩΝ ΕΛΕΓΧΩΝ." printed as the work\'s own opening line/incipit in this Bekker edition (verified: it is a genuine <p>, not a mis-tagged <head>) - kept verbatim as real source content, not stripped as apparatus.',
  },
  {
    workId: 'de-caelo-grc',
    tlg: 'tlg005',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg005.1st1K-grc1.xml',
    titleGrc: 'Περὶ οὐρανοῦ',
    titleConventional: 'On the Heavens',
    editor: 'Carl Prantl',
    edition: 'Aristoteles de coelo et de generatione et corruptione (Prantl, ed., Teubner, 1881)',
    pubPlace: 'Leipzig',
    publisher: 'Teubner',
    date: '1881',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'book-chapter', bookSubtype: 'book', chapterSubtype: 'chapter' },
    expectedBooks: 4,
    expectedChapters: 39,
  },
  {
    workId: 'de-generatione-et-corruptione-grc',
    tlg: 'tlg013',
    source: 'first1k',
    witness: '1st1K-grc2',
    file: 'tlg0086.tlg013.1st1K-grc2.xml',
    titleGrc: 'Περὶ γενέσεως καὶ φθορᾶς',
    titleConventional: 'On Generation and Corruption',
    editor: 'Carl Prantl',
    edition: 'Aristoteles de coelo et de generatione et corruptione (Prantl, ed., Teubner, 1881)',
    pubPlace: 'Leipzig',
    publisher: 'Teubner',
    date: '1881',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'book-chapter', bookSubtype: 'book', chapterSubtype: 'chapter' },
    expectedBooks: 2,
    expectedChapters: 20,
    bibliographicNote:
      'F1K offers two witnesses for this work: grc1 (E. S. Forster\'s 1955 Loeb, in the volume "On Sophistical Refutations, On Coming-to-be and Passing-away, On the Cosmos") and grc2 (Prantl 1881, the same Teubner edition/volume used here for De Caelo). grc2 was deliberately chosen for edition consistency with De Caelo - see the module doc comment above.',
  },
  {
    workId: 'meteorologica-grc',
    tlg: 'tlg026',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg026.1st1K-grc1.xml',
    titleGrc: 'Μετεωρολογικά',
    titleConventional: 'Meteorology',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 3 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'book-chapter', bookSubtype: 'book', chapterSubtype: 'chapter' },
    expectedBooks: 4,
    expectedChapters: 41,
  },
  {
    workId: 'de-anima-grc',
    tlg: 'tlg002',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg002.1st1K-grc1.xml',
    titleGrc: 'Περὶ ψυχῆς',
    titleConventional: 'On the Soul',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 3 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: false,
    englishNote:
      'No English translation is bundled: J. A. Smith\'s 1931 translation (Oxford, in the Ross-edited "Works of Aristotle" series) is still under copyright, and R. D. Hicks\'s 1907 translation (public domain) exists today only as unproofread OCR of a scanned printing, which this library does not ship as reading text; a proofread source may be added later.',
    shape: { kind: 'book-chapter', bookSubtype: 'book', chapterSubtype: 'chapter' },
    expectedBooks: 3,
    expectedChapters: 30,
  },
  {
    workId: 'de-sensu-grc',
    tlg: 'tlg041',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg041.1st1K-grc1.xml',
    titleGrc: 'Περὶ αἰσθήσεως καὶ αἰσθητῶν',
    titleConventional: 'On Sense and Sensible Objects',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 3 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 7,
  },
  {
    workId: 'de-memoria-grc',
    tlg: 'tlg024',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg024.1st1K-grc1.xml',
    titleGrc: 'Περὶ μνήμης καὶ ἀναμνήσεως',
    titleConventional: 'On Memory and Recollection',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 3 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 2,
  },
  {
    workId: 'de-somno-grc',
    tlg: 'tlg042',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg042.1st1K-grc1.xml',
    titleGrc: 'Περὶ ὕπνου καὶ ἐγρηγόρσεως',
    titleConventional: 'On Sleep and Waking',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 3 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 3,
  },
  {
    workId: 'de-insomniis-grc',
    tlg: 'tlg016',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg016.1st1K-grc1.xml',
    titleGrc: 'Περὶ ἐνυπνίων',
    titleConventional: 'On Dreams',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 3 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 3,
  },
  {
    workId: 'de-divinatione-per-somnum-grc',
    tlg: 'tlg008',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg008.1st1K-grc1.xml',
    titleGrc: 'Περὶ τῆς καθ᾽ ὕπνον μαντικῆς',
    titleConventional: 'On Divination in Sleep',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 3 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 2,
  },
  {
    workId: 'de-longitudine-grc',
    tlg: 'tlg020',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg020.1st1K-grc1.xml',
    titleGrc: 'Περὶ μακροβιότητος καὶ βραχυβιότητος',
    titleConventional: 'On Length and Shortness of Life',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 3 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 6,
  },
  {
    workId: 'de-iuventute-grc',
    tlg: 'tlg018',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg018.1st1K-grc1.xml',
    titleGrc: 'Περὶ νεότητος καὶ γήρως, ζωῆς καὶ θανάτου',
    titleConventional: 'On Youth, Old Age, Life and Death',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 3 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 6,
  },
  {
    workId: 'de-respiratione-grc',
    tlg: 'tlg037',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg037.1st1K-grc1.xml',
    titleGrc: 'Περὶ ἀναπνοῆς',
    titleConventional: 'On Respiration',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 3 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 21,
  },
  {
    workId: 'historia-animalium-grc',
    tlg: 'tlg014',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg014.1st1K-grc1.xml',
    titleGrc: 'Τῶν περὶ τὰ ζῷα ἱστοριῶν',
    titleConventional: 'History of Animals',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 4 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'book-chapter', bookSubtype: 'book', chapterSubtype: 'chapter' },
    expectedBooks: 10,
    expectedChapters: 238,
  },
  {
    workId: 'de-partibus-animalium-grc',
    tlg: 'tlg030',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg030.1st1K-grc1.xml',
    titleGrc: 'Περὶ ζῴων μορίων',
    titleConventional: 'Parts of Animals',
    editor: 'Bernhard Langkavel',
    edition: 'Aristotelis De partibus animalium libri quattuor (Langkavel, ed., Teubner, 1868)',
    pubPlace: 'Leipzig',
    publisher: 'Teubner',
    date: '1868',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'book-chapter', bookSubtype: 'book', chapterSubtype: 'chapter' },
    expectedBooks: 4,
    expectedChapters: 50,
    keepBareNotes: true,
    bibliographicNote:
      'A stretch of Book 4 (around the traditional chapters on bird/quadruped locomotion) carries 19 bare `<note>` spans (no `type` attribute - distinct from this file\'s ordinary `<note type="marginal">` Bekker citations) holding, verbatim, up to ~1.5KB of running Greek prose each, several explicitly labelled in the source itself "editio prior." / "editio posterior (cod. Y)." - i.e. Langkavel\'s edition preserves TWO parallel variant recensions of this stretch side by side, not a short editorial comment. Discarding them (this importer\'s default policy for a non-citation <note>) would silently delete real ancient text - one chapter (book-4-ch-12) would end up with zero passages at all, caught by this importer\'s own raw-vs-imported coverage check. Both variants are therefore kept, verbatim, inline (unwrapped rather than discarded) - meaning this stretch of the reading text visibly repeats similar content in two slightly different phrasings, exactly as the source itself preserves it, rather than this importer silently picking one recension or merging them.',
  },
  {
    workId: 'de-motu-animalium-grc',
    tlg: 'tlg021',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg021.1st1K-grc1.xml',
    titleGrc: 'Περὶ ζῴων κινήσεως',
    titleConventional: 'On the Movement of Animals',
    editor: 'Werner Jaeger',
    edition: 'Aristotelis De animalium motione et De animalium incessu (Jaeger, ed., Teubner, 1913)',
    pubPlace: 'Leipzig',
    publisher: 'Teubner',
    date: '1913',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 11,
  },
  {
    workId: 'de-incessu-animalium-grc',
    tlg: 'tlg015',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg015.1st1K-grc1.xml',
    titleGrc: 'Περὶ ζῴων πορείας',
    titleConventional: 'On the Gait of Animals',
    editor: 'Werner Jaeger',
    edition: 'Aristotelis De animalium motione et De animalium incessu (Jaeger, ed., Teubner, 1913)',
    pubPlace: 'Leipzig',
    publisher: 'Teubner',
    date: '1913',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 19,
  },
  {
    workId: 'de-generatione-animalium-grc',
    tlg: 'tlg012',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg012.1st1K-grc1.xml',
    titleGrc: 'Περὶ ζῴων γενέσεως',
    titleConventional: 'Generation of Animals',
    editor: 'Immanuel Bekker',
    edition: 'De Generatione Animalium, Libri Quinque (Bekker, ed., G. Reimer, 1829)',
    pubPlace: 'Berlin',
    publisher: 'Typis Academicis, G. Reimer',
    date: '1829',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'book-chapter', bookSubtype: 'book', chapterSubtype: 'chapter' },
    expectedBooks: 5,
    expectedChapters: 60,
  },
  {
    workId: 'eudemian-ethics-grc',
    tlg: 'tlg009',
    source: 'perseus',
    witness: 'perseus-grc2',
    file: 'tlg0086.tlg009.perseus-grc2.xml',
    titleGrc: 'Ἠθικὰ Εὐδήμεια',
    titleConventional: 'Eudemian Ethics',
    editor: 'Franz Susemihl',
    edition: 'Aristotelis Ethica Eudemia. Eudemi Rhodii Ethica. (Susemihl, ed., Teubner, 1884)',
    pubPlace: 'Leipzig',
    publisher: 'Teubner',
    date: '1884',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'book-chapter', bookSubtype: 'book', chapterSubtype: 'section' },
    expectedBooks: 5,
    expectedChapters: 41,
    bibliographicNote:
      'This edition\'s own book divisions are `n="1","2","3","7","8"` - NOT a renumbered 1-5. Books 4-6 of the Eudemian Ethics are the three "common books" also transmitted as Nicomachean Ethics V-VII, and Susemihl\'s Teubner text (like most editions) prints only the books unique to the Eudemian Ethics, leaving the traditional numbering gap rather than renumbering around it. This importer preserves that gap (Book divisions here are 1,2,3,7,8, not 1-5) instead of manufacturing false continuity.',
  },
  {
    workId: 'magna-moralia-grc',
    tlg: 'tlg022',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg022.1st1K-grc1.xml',
    titleGrc: 'Ἠθικὰ μεγάλα',
    titleConventional: 'Magna Moralia',
    editor: 'Franz Susemihl',
    edition: 'Aristotelis Quae Feruntur Magna Moralia (Susemihl, ed., Teubner, 1883)',
    pubPlace: 'Leipzig',
    publisher: 'Teubner',
    date: '1883',
    authenticity: 'disputed',
    englishBundledConcurrently: false,
    englishNote:
      'No English translation is bundled: the only public-domain English translation (St. George Stock, 1915, in the Ross-edited "Works of Aristotle" series) exists today only as unproofread OCR of a scanned printing, which this library does not ship as reading text; a proofread source may be added later.',
    shape: { kind: 'book-chapter', bookSubtype: 'book', chapterSubtype: 'chapter' },
    expectedBooks: 2,
    expectedChapters: 51,
  },
  {
    workId: 'politics-grc',
    tlg: 'tlg035',
    source: 'perseus',
    witness: 'perseus-grc2',
    file: 'tlg0086.tlg035.perseus-grc2.xml',
    titleGrc: 'Πολιτικά',
    titleConventional: 'Politics',
    editor: 'William David Ross',
    edition: 'Aristotelis Politica (Ross, ed., Clarendon Press, 1957 printing)',
    pubPlace: 'Oxford',
    publisher: 'Clarendon Press',
    date: '1957',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'book-page', bookSubtype: 'book', pageSubtype: 'bekker_page' },
    expectedBooks: 8,
    expectedChapters: 189,
    bibliographicNote:
      'Ross\'s 1957 Oxford Classical Text is a 20th-century critical edition; the ancient Greek text itself is public-domain-eligible ancient content (the same licence wording already used in this app for Archimedes/Mugler and Euclid), but Ross\'s own apparatus/reconstruction is not independently public domain - only the digitisation\'s CC BY-SA licence is relied on here, as instructed. This source divides directly at every Bekker PAGE (`bekker_page` div, e.g. n="1252a") with no separate chapter-numbering level at all in the XML - so each Chapter in this app is one Bekker page\'s worth of text, numbered sequentially within its Book, with Division.ref carrying the real citation (e.g. "1252a").',
  },
  {
    workId: 'economics-grc',
    tlg: 'tlg029',
    source: 'perseus',
    witness: 'perseus-grc2',
    file: 'tlg0086.tlg029.perseus-grc2.xml',
    titleGrc: 'Οἰκονομικά',
    titleConventional: 'Economics',
    editor: 'George Cyril Armstrong',
    edition: 'Metaphysics; Oeconomica and Magna Moralia (Armstrong, ed., Loeb Classical Library, William Heinemann / Harvard University Press, 1935 printing)',
    pubPlace: 'London',
    publisher: 'William Heinemann Ltd.',
    date: '1935',
    authenticity: 'pseudo',
    englishBundledConcurrently: false,
    englishNote:
      'No English translation is bundled: the only public-domain English translation (E. S. Forster, 1920, in the Ross-edited "Works of Aristotle" series) exists today only as unproofread OCR of a scanned printing, which this library does not ship as reading text; a proofread source may be added later.',
    shape: { kind: 'book-chapter', bookSubtype: 'book', chapterSubtype: 'section' },
    expectedBooks: 2,
    expectedChapters: 8,
    bibliographicNote:
      'Only 2 Books survive in Greek (the traditional Book III survives only in a medieval Latin version, not Greek, so is absent here by the nature of the transmission, not an import gap).',
  },
  {
    workId: 'rhetoric-grc',
    tlg: 'tlg038',
    source: 'perseus',
    witness: 'perseus-grc2',
    file: 'tlg0086.tlg038.perseus-grc2.xml',
    titleGrc: 'Ῥητορική',
    titleConventional: 'Rhetoric',
    editor: 'William David Ross',
    edition: 'Aristotelis Ars Rhetorica (Ross, ed., Clarendon Press, 1959 printing)',
    pubPlace: 'Oxford',
    publisher: 'Clarendon Press',
    date: '1959',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'book-chapter', bookSubtype: 'book', chapterSubtype: 'chapter' },
    expectedBooks: 3,
    expectedChapters: 60,
    bibliographicNote:
      'Ross\'s 1959 Oxford Classical Text is a 20th-century critical edition; only the ancient text\'s public-domain-eligible status and the digitisation\'s CC BY-SA licence are relied on, per the same policy as Politics above.',
  },
  {
    workId: 'poetics-grc',
    tlg: 'tlg034',
    source: 'digicorpus',
    witness: 'digicorpus-grc2',
    file: 'tlg0086.tlg034.digicorpus-grc2.xml',
    titleGrc: 'Περὶ ποιητικῆς',
    titleConventional: 'Poetics',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 11 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'authentic',
    englishBundledConcurrently: true,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 26,
    bibliographicNote: 'digicorpus-grc2 (Bekker 1837) chosen over perseus-grc2 (Kassel 1965) - see the module doc comment above.',
  },
  {
    workId: 'athenian-constitution-grc',
    tlg: 'tlg003',
    source: 'perseus',
    witness: 'perseus-grc2',
    file: 'tlg0086.tlg003.perseus-grc2.xml',
    titleGrc: 'Ἀθηναίων πολιτεία',
    titleConventional: 'The Athenian Constitution',
    editor: 'Frederic G. Kenyon',
    edition: 'Aristotelis Atheniensium Respublica (Kenyon, ed., Clarendon Press, 1920)',
    pubPlace: 'Oxford',
    publisher: 'Clarendon Press',
    date: '1920',
    authenticity: 'disputed',
    englishBundledConcurrently: true,
    shape: { kind: 'flat-chapter', chapterSubtype: 'section' },
    expectedBooks: null,
    expectedChapters: 73,
    bibliographicNote:
      'Discovered only in 1890 (on an Egyptian papyrus), so it carries no Bekker page citation at all - Kenyon\'s own chapter numbering (1-69, plus a handful of numbered fragments of the lost opening, e.g. "frag_2") is the only citation scheme and is used here as-is for Division.number.',
  },
  {
    workId: 'virtues-and-vices-grc',
    tlg: 'tlg045',
    source: 'perseus',
    witness: 'perseus-grc2',
    file: 'tlg0086.tlg045.perseus-grc2.xml',
    titleGrc: 'περὶ Ἀρετῶν καὶ Κακιῶν',
    titleConventional: 'On Virtues and Vices',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 2 (Bekker, ed., Reimer, 1831)',
    pubPlace: 'Berlin',
    publisher: 'Reimer',
    date: '1831',
    authenticity: 'pseudo',
    englishBundledConcurrently: true,
    shape: { kind: 'flat-paragraph', wrapperSubtype: 'section' },
    expectedBooks: null,
    expectedChapters: 7,
    bibliographicNote:
      'This source has no chapter-level division at all: the entire work is one wrapper div (`subtype="section" n="1249"`, its Bekker starting page) holding exactly 7 bare `<p>` paragraphs (verified by direct count) - one fewer than the work\'s traditional 8-chapter division (this transcription runs two of the traditional chapters together into a single paragraph rather than breaking them, most likely at the low-salience break between chs. 6 and 7); each `<p>` here is imported as its own flat chapter (ch-1..ch-7) rather than forcing an 8th split the source itself does not make. Its Bekker citations are tagged `<milestone unit="section" resp="bekker" n="1249a">` (not `unit="page"` as elsewhere in this corpus) - recognised by this importer\'s value-pattern check (a citation is identified by looking like "1249a", not by its `unit=` attribute literally saying "page").',
  },
  {
    workId: 'mechanica-grc',
    tlg: 'tlg023',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg023.1st1K-grc1.xml',
    titleGrc: 'Μηχανικά',
    titleConventional: 'Mechanical Problems',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 6 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'pseudo',
    englishBundledConcurrently: false,
    englishNote:
      'No English translation is bundled: the only public-domain English translation (E. S. Forster, 1913, in the Ross-edited "Works of Aristotle" series) exists today only as unproofread OCR of a scanned printing, which this library does not ship as reading text; a proofread source may be added later.',
    shape: { kind: 'problem-section', problemSubtype: 'chapter', sectionSubtype: 'section' },
    expectedBooks: 36,
    expectedChapters: 158,
    bibliographicNote:
      'This source divides the work into 36 `chapter` divs numbered n="0" to n="35": n="0" is the treatise\'s unnumbered preface (13 sections) and n="1"-"35" are the traditional numbered Problems, each holding its own `section` numbering that restarts at 1 (158 sections in all). They are imported as a two-level tree - a "Preface" division and Problems 1-35, each with its sections as leaves (ids `preface-ch-M`, `problem-N-ch-M`) - so every division id is unique. (An earlier build of this library folded the sections into one flat `ch-N` list, which silently produced duplicate ids because the section numbers restart in every problem; that is what the two-level scheme replaces.)',
  },
  {
    workId: 'problemata-grc',
    tlg: 'tlg036',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg036.1st1K-grc1.xml',
    titleGrc: 'Ἀριστοτέλους φυσικὰ προβλήματα κατ᾿ εἶδος συναγωγῆς',
    titleConventional: 'Problems',
    editor: 'Charles Ruelle',
    edition: 'Aristotelis Quae Feruntur Problemata Physica (Ruelle, ed., Teubner, 1922)',
    pubPlace: 'Leipzig',
    publisher: 'Teubner',
    date: '1922',
    authenticity: 'pseudo',
    englishBundledConcurrently: false,
    englishNote:
      'No English translation is bundled: the only public-domain English translation (E. S. Forster, 1927, in the Ross-edited "Works of Aristotle" series) exists today only as unproofread OCR of a scanned printing, which this library does not ship as reading text; a proofread source may be added later.',
    shape: { kind: 'book-chapter', bookSubtype: 'book', chapterSubtype: 'chapter' },
    expectedBooks: 38,
    expectedChapters: 889,
  },
  {
    workId: 'de-coloribus-grc',
    tlg: 'tlg007',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg007.1st1K-grc1.xml',
    titleGrc: 'Περὶ χρωμάτων',
    titleConventional: 'On Colours',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 6 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'pseudo',
    englishBundledConcurrently: false,
    englishNote: MINOR_OPUSCULA_NOTE,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 6,
  },
  {
    workId: 'de-audibilibus-grc',
    tlg: 'tlg004',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg004.1st1K-grc1.xml',
    titleGrc: 'Ἐκ τοῦ περὶ ἀκουστῶν',
    titleConventional: 'On Things Heard',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 6 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'pseudo',
    englishBundledConcurrently: false,
    englishNote: MINOR_OPUSCULA_NOTE,
    shape: { kind: 'flat-chapter', chapterSubtype: 'section' },
    expectedBooks: null,
    expectedChapters: 74,
  },
  {
    workId: 'physiognomonica-grc',
    tlg: 'tlg032',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg032.1st1K-grc1.xml',
    titleGrc: 'Φυσιογνωμονικά',
    titleConventional: 'Physiognomonics',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 6 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'pseudo',
    englishBundledConcurrently: false,
    englishNote: MINOR_OPUSCULA_NOTE,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 6,
  },
  {
    workId: 'de-plantis-grc',
    tlg: 'tlg039',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg039.1st1K-grc1.xml',
    titleGrc: 'Περὶ φυτῶν',
    titleConventional: 'On Plants',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 6 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'pseudo',
    englishBundledConcurrently: true,
    shape: { kind: 'book-chapter', bookSubtype: 'part', chapterSubtype: 'chapter' },
    expectedBooks: 3,
    expectedChapters: 18,
    bibliographicNote:
      'This source divides into 3 `part`s: `n="prol"` (a short prologue, 1 chapter), then `n="1"`, `n="2"` (the traditional two books). Imported as 3 sequential Books (Book 1 = the prologue, editorialTitle "prol" preserved) rather than folding the prologue into Book 1, since the source itself divides it out as a structural peer of the two main books.',
  },
  {
    workId: 'de-mirabilibus-grc',
    tlg: 'tlg027',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg027.1st1K-grc1.xml',
    titleGrc: 'Περὶ θαυμασίων ἀκουσμάτων',
    titleConventional: 'On Marvellous Things Heard',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 6 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'pseudo',
    englishBundledConcurrently: false,
    englishNote: MINOR_OPUSCULA_NOTE,
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 178,
  },
  {
    workId: 'de-lineis-insecabilibus-grc',
    tlg: 'tlg019',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg019.1st1K-grc1.xml',
    titleGrc: 'Περὶ ἀτόμων γραμμῶν',
    titleConventional: 'On Indivisible Lines',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 6 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'pseudo',
    englishBundledConcurrently: false,
    englishNote: MINOR_OPUSCULA_NOTE,
    shape: { kind: 'flat-chapter', chapterSubtype: 'section' },
    expectedBooks: null,
    expectedChapters: 60,
  },
  {
    workId: 'de-ventis-grc',
    tlg: 'tlg046',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg046.1st1K-grc1.xml',
    titleGrc: 'Ἀνέμων θέσεις καὶ προσηγορίαι',
    titleConventional: 'On the Situations and Names of Winds',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 6 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'pseudo',
    englishBundledConcurrently: false,
    englishNote: MINOR_OPUSCULA_NOTE,
    shape: { kind: 'flat-chapter', chapterSubtype: 'section' },
    expectedBooks: null,
    expectedChapters: 8,
    bibliographicNote:
      'The source\'s own `section` numbering skips n="2" and n="3" entirely (it runs 1, 4, 5, 6, 7, 8, 9, 10 - 8 divisions total) - a gap in this transcription, preserved and logged rather than renumbered.',
  },
  {
    workId: 'de-melisso-xenophane-gorgia-grc',
    tlg: 'tlg047',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg047.1st1K-grc1.xml',
    titleGrc: 'Περὶ Ξενοφάνους, περὶ Ζήνωνος, περὶ Γοργίου',
    titleConventional: 'On Melissus, Xenophanes, and Gorgias',
    editor: 'Immanuel Bekker',
    edition: 'Aristotelis Opera, Volume 6 (Bekker, ed., Oxford University Press, 1837)',
    pubPlace: 'Oxford',
    publisher: 'Oxford University Press',
    date: '1837',
    authenticity: 'pseudo',
    englishBundledConcurrently: false,
    englishNote: MINOR_OPUSCULA_NOTE,
    shape: { kind: 'book-chapter', bookSubtype: 'part', chapterSubtype: 'chapter' },
    expectedBooks: 3,
    expectedChapters: 6,
    bibliographicNote: 'See the module doc comment above for the Melissus/Zeno title discrepancy this source\'s own part labels reveal.',
  },
  {
    workId: 'de-spiritu-grc',
    tlg: 'tlg043',
    source: 'first1k',
    witness: '1st1K-grc1',
    file: 'tlg0086.tlg043.1st1K-grc1.xml',
    titleGrc: 'Περὶ πνεύματος',
    titleConventional: 'On Breath',
    editor: 'Werner Jaeger',
    edition: '(per this file\'s own, likely erroneous, <sourceDesc>) "Aristotelis De animalium motione et De animalium incessu", Jaeger, ed., Teubner, 1913 - see the module doc comment above',
    pubPlace: 'Leipzig',
    publisher: 'Teubner',
    date: '1913',
    authenticity: 'pseudo',
    englishBundledConcurrently: false,
    englishNote:
      'No English translation is bundled: the only public-domain English translation (J. F. Dobson, publication date unverified, in the Ross-edited "Works of Aristotle" series) exists today only as unproofread OCR of a scanned printing, which this library does not ship as reading text; a proofread source may be added later.',
    shape: { kind: 'flat-chapter', chapterSubtype: 'chapter' },
    expectedBooks: null,
    expectedChapters: 9,
  },
] as const;

export const SKIPPED_WORKS = [
  {
    workId: 'de-mundo-grc',
    reason:
      'De Mundo (Περὶ κόσμου) does not exist under any tlg number in either the First1KGreek or the Perseus/OGL canonical-greekLit repository for Aristotle (tlg0086) - see the module doc comment above for the full verification.',
  },
] as const;
