/**
 * Structural mirror of the generic-work content types in `src/library/types.ts`
 * (Passage / Division / GenericWork / WorkAbout*), used internally by this
 * Dante import batch. Not one of the per-work `data/<workId>/types.ts`
 * outputs - those are generated byte-identical copies (see typesTemplate.ts),
 * exactly like every other importer in this repo (e.g.
 * scripts/import-greek-drama-shared/genericTypes.ts).
 */

export type Lang = 'it' | 'en' | 'la';

export interface Passage {
  /** printed citation number for this passage, or '' when the source gives none */
  n: string;
  /** verbatim text */
  text: string;
  /** optional citation string, or null */
  ref: string | null;
  /** optional note when something irregular was preserved */
  anomaly?: string;
}

export interface Division {
  id: string;
  number: string | null;
  ref: string | null;
  sourceHeading: string | null;
  editorialTitle: string | null;
  children: Division[];
  passages: Passage[];
}

export interface GenericWork {
  workId: string;
  language: Lang;
  divisions: Division[];
}

export interface WorkAboutSection {
  heading: string;
  paragraphs: string[];
}

export interface WorkAbout {
  workId: string;
  title: string;
  author: string;
  language: Lang;
  edition?: string;
  editor?: string;
  translator?: string;
  provenance: string;
  license: string;
  sections?: WorkAboutSection[];
}

export interface Anomaly {
  where: string;
  note: string;
}
